//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PicoScopeFRA.rc
//
#define IDS_APP_TITLE                   100
#define IDD_SETTINGS                    102
#define IDD_INTERACTIVE_RETRY           104
#define IDD_MAIN                        200
#define IDD_ABOUTBOX                    201
#define IDD_SCOPESELECTORBOX            202
#define IDD_AXES_DIALOG                 203
#define IDM_EXIT                        300
#define IDM_SAVE                        301
#define IDM_SAVEAS                      302
#define IDM_EXPORTDATA                  303
#define IDM_EXPORTDATAAS                304
#define IDM_CAL                         305
#define IDM_SETTINGS                    306
#define IDM_ABOUT                       307
#define IDM_CONNECT_SCOPE               308
#define IDM_PRINTPLOT                   309
#define IDI_PICOSCOPEFRA                400
#define IDI_SMALL                       401
#define IDC_PICOSCOPEFRA                500
#define IDC_MYICON                      501
#define IDC_CANCEL                      502
#define IDC_GO                          503
#define IDC_INPUT_CHANNEL               504
#define IDC_INPUT_ATTEN                 505
#define IDC_INPUT_COUPLING              506
#define IDC_INPUT_DC_OFFS               507
#define IDC_INPUT_BWLIM                 508
#define IDC_OUTPUT_CHANNEL              509
#define IDC_OUTPUT_ATTEN                510
#define IDC_OUTPUT_COUPLING             511
#define IDC_OUTPUT_DC_OFFS              512
#define IDC_OUTPUT_BWLIM                513
#define IDC_STIMULUS_VPP                514
#define IDC_FRA_START_FREQ              515
#define IDC_FRA_STOP_FREQ               516
#define IDC_FRA_STEPS_PER_DECADE        517
#define IDC_FRA_AUTO_AXES               518
#define IDC_FRA_SAVED_AXES              519
#define IDC_FRA_DRAW_GAIN               520
#define IDC_FRA_DRAW_PHASE              521
#define IDC_FRA_DRAW_GM                 522
#define IDC_FRA_DRAW_PM                 523
#define IDC_FRA_UNWRAP_PHASE            524
#define IDC_RIGHTMOST_CTL               525
#define IDC_STATUS_TEXT                 526
#define IDC_LOG                         527
#define IDC_COPY                        528
#define IDC_CLEAR                       529
#define IDC_AUTOCLEAR                   530
#define IDC_RESPONSE_TARGET             531
#define IDC_MAX_STIMULUS_VPP            532
#define IDC_SCOPE_SELECT_LIST           535
#define IDC_FREQ_AXIS_AUTOSCALE         540
#define IDC_GAIN_AXIS_AUTOSCALE         541
#define IDC_PHASE_AXIS_AUTOSCALE        542
#define IDC_FREQ_AXIS_MIN               543
#define IDC_GAIN_AXIS_MIN               544
#define IDC_PHASE_AXIS_MIN              545
#define IDC_FREQ_AXIS_MAX               546
#define IDC_GAIN_AXIS_MAX               547
#define IDC_PHASE_AXIS_MAX              548
#define IDC_FREQ_AXIS_MAJ_INT           549
#define IDC_GAIN_AXIS_MAJ_INT           550
#define IDC_PHASE_AXIS_MAJ_INT          551
#define IDC_FREQ_AXIS_TICKS_PER_MAJOR   552
#define IDC_GAIN_AXIS_TICKS_PER_MAJOR   553
#define IDC_PHASE_AXIS_TICKS_PER_MAJOR  554
#define IDC_FREQ_AXIS_MAJOR_GRIDS       555
#define IDC_GAIN_AXIS_MAJOR_GRIDS       556
#define IDC_PHASE_AXIS_MAJOR_GRIDS      557
#define IDC_FREQ_AXIS_MINOR_GRIDS       558
#define IDC_GAIN_AXIS_MINOR_GRIDS       559
#define IDC_PHASE_AXIS_MINOR_GRIDS      560
#define IDC_GAIN_AXIS_MASTER_GRIDS      561
#define IDC_PHASE_AXIS_MASTER_GRIDS     562
#define IDC_APPID                       563
#define IDC_STORE                       564
#define IDC_TEXT_1                      570
#define IDC_TEXT_2                      571
#define IDC_TEXT_3                      572
#define IDC_TEXT_4                      573
#define IDC_TEXT_5                      574
#define IDC_TEXT_6                      575
#define IDC_TEXT_7                      576
#define IDC_TEXT_8                      577
#define IDC_TEXT_9                      578
#define IDC_TEXT_10                     579
#define IDC_TEXT_11                     580
#define IDC_TEXT_12                     581
#define IDC_TEXT_STIMULUS_TITLE         582
#define IDC_TEXT_14                     583
#define IDC_TEXT_15                     584
#define IDC_TEXT_16                     585
#define IDC_TEXT_17                     586
#define IDC_TEXT_18                     587
#define IDC_TEXT_19                     588
#define IDC_TEXT_20                     589
#define IDC_TEXT_21                     590
#define IDC_TEXT_22                     591
#define IDC_TEXT_23                     592
#define IDC_TEXT_24                     593
#define IDC_TEXT_25                     594
#define IDC_TEXT_26                     595
#define IDC_TEXT_27                     596
#define IDC_TEXT_RESPONSE_TARGET_TITLE  597
#define IDC_TEXT_RESPONSE_TARGET_UNITS  598
#define IDC_TEXT_MAX_STIMULUS_VPP_TITLE 599
#define IDC_TEXT_MAX_STIMULUS_VPP_UNITS 600
#define IDR_MAINFRAME                   601
#define IDB_PLOT_UNAVAILABLE            700
#define IDB_SEPARATOR                   701
#define IDC_RADIO_LOW_NOISE_MODE        1000
#define IDC_RADIO_NOISE_REJECT_MODE     1001
#define IDC_RADIO_SWEEP_ASCENDING       1002
#define IDC_RADIO_SWEEP_DESCENDING      1003
#define IDC_EDIT_PHASE_WRAPPING_THRESHOLD 1004
#define IDC_EDIT_GAIN_MARGIN_PHASE_CROSSOVER 1005
#define IDC_BUTTON_AXIS_SETTINGS        1006
#define IDC_BUTTON_PLOT_COLORS          1007
#define IDC_TIME_DOMAIN_DIAGNOSTIC_PLOTS_ENABLE 1008
#define IDC_COMBO1                      1010
#define IDC_EDIT_AUTORANGE_TRIES_PER_STEP 1011
#define IDC_EDIT_PURITY_LOWER_LIMIT     1012
#define IDC_EDIT_PURITY_LOWER_QUALITY_LIMIT 1012
#define IDC_EDIT_AMPLITUDE_LOWER_QUALITY_LIMIT 1013
#define IDC_EDIT_EXTRA_SETTLING_TIME    1014
#define IDC_EDIT_FRA_MAXIMUM_CYCLES_CAPTURED 1015
#define IDC_EDIT_AUTORANGE_TOLERANCE    1016
#define IDC_EDIT_FRA_MINIMUM_CYCLES_CAPTURED 1017
#define IDC_COMBO_SCOPE_SELECTOR        1018
#define IDC_EDIT_NOISE_REJECT_TIMEBASE  1019
#define IDC_EDIT_FRA_LOW_NOISE_OVERSAMPLING 1020
#define IDC_COMBO_INPUT_START_RANGE     1021
#define IDC_EDIT_FRA_NOISE_REJECT_BW    1022
#define IDC_ADAPTIVE_STIMULUS_ENABLE    1023
#define IDC_QUALITY_LIMITS_ENABLE       1024
#define IDC_EXCLUDE_DC_FROM_NOISE       1025
#define IDC_COMBO_OUTPUT_START_RANGE    1026
#define IDC_EDIT_ADAPTIVE_STIMULUS_TRIES_PER_STEP 1027
#define IDC_RL_STEP_HISTORY_BUTTON      1028
#define IDC_EDIT_ADAPTIVE_STIMULUS_RESPONSE_TARGET_TOLERANCE 1028
#define IDC_RL_AUTORANGE_N_OF_M         1029
#define IDC_RL_ADAPTIVE_STIMULUS_N_OF_M 1030
#define IDC_RL_INPUT_CHANNEL_RANGE      1031
#define IDC_RL_OUTPUT_CHANNEL_RANGE     1032
#define IDC_RL_INPUT_CHANNEL_STATUS     1033
#define IDC_RL_OUTPUT_CHANNEL_STATUS    1034
#define IDC_RL_STIMULUS_VPP             1035
#define IDC_RL_INPUT_RESPONSE_AMPLITUDE 1036
#define IDC_RL_OUTPUT_RESPONSE_AMPLITUDE 1037
#define IDC_RL_ADJUST_SETUP_BUTTON      1038
#define IDC_RL_AS_GRP                   1040
#define IDC_STATIC_FRA_NOISE_REJECT_BW  1042
#define IDC_STATIC_PURITY_LOWER_QUALITY_LIMIT 1043
#define IDC_STATIC_AMPLITUDE_LOWER_QUALITY_LIMIT 1044
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
